version: '2'

services:
  docker-vulpy_latest:
    build: .
    volumes:
      - .:/vulpy
      - ./contrast_security.yaml:/app/vulpy/bad/contrast_security.yaml
    container_name: vulpy-contrast
    ports:
      - "5002:5002"
